# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/ethresearch/sharding-p2p-poc/pb/event/event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from github.com.ethresearch.sharding_p2p_poc.pb.message import message_pb2 as github_dot_com_dot_ethresearch_dot_sharding__p2p__poc_dot_pb_dot_message_dot_message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.com/ethresearch/sharding-p2p-poc/pb/event/event.proto',
  package='proto.event',
  syntax='proto3',
  serialized_pb=_b('\n<github.com/ethresearch/sharding-p2p-poc/pb/event/event.proto\x12\x0bproto.event\x1a@github.com/ethresearch/sharding-p2p-poc/pb/message/message.proto\"\t\n\x07MetaMsg\"j\n\x14NewCollationNotifier\x12%\n\x07metaMsg\x18\x01 \x01(\x0b\x32\x14.proto.event.MetaMsg\x12+\n\tcollation\x18\x02 \x01(\x0b\x32\x18.proto.message.Collation\"P\n\x14NewCollationResponse\x12\'\n\x08response\x18\x01 \x01(\x0b\x32\x15.proto.event.Response\x12\x0f\n\x07isValid\x18\x02 \x01(\x08\"\\\n\x08Response\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.proto.event.Response.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32_\n\x05\x45vent\x12V\n\x0cNewCollation\x12!.proto.event.NewCollationNotifier\x1a!.proto.event.NewCollationResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[github_dot_com_dot_ethresearch_dot_sharding__p2p__poc_dot_pb_dot_message_dot_message__pb2.DESCRIPTOR,])



_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='proto.event.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=402,
  serialized_end=436,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)


_METAMSG = _descriptor.Descriptor(
  name='MetaMsg',
  full_name='proto.event.MetaMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=152,
)


_NEWCOLLATIONNOTIFIER = _descriptor.Descriptor(
  name='NewCollationNotifier',
  full_name='proto.event.NewCollationNotifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metaMsg', full_name='proto.event.NewCollationNotifier.metaMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collation', full_name='proto.event.NewCollationNotifier.collation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=260,
)


_NEWCOLLATIONRESPONSE = _descriptor.Descriptor(
  name='NewCollationResponse',
  full_name='proto.event.NewCollationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='proto.event.NewCollationResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isValid', full_name='proto.event.NewCollationResponse.isValid', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=342,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='proto.event.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.event.Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=436,
)

_NEWCOLLATIONNOTIFIER.fields_by_name['metaMsg'].message_type = _METAMSG
_NEWCOLLATIONNOTIFIER.fields_by_name['collation'].message_type = github_dot_com_dot_ethresearch_dot_sharding__p2p__poc_dot_pb_dot_message_dot_message__pb2._COLLATION
_NEWCOLLATIONRESPONSE.fields_by_name['response'].message_type = _RESPONSE
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE_STATUS.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['MetaMsg'] = _METAMSG
DESCRIPTOR.message_types_by_name['NewCollationNotifier'] = _NEWCOLLATIONNOTIFIER
DESCRIPTOR.message_types_by_name['NewCollationResponse'] = _NEWCOLLATIONRESPONSE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaMsg = _reflection.GeneratedProtocolMessageType('MetaMsg', (_message.Message,), dict(
  DESCRIPTOR = _METAMSG,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.MetaMsg)
  ))
_sym_db.RegisterMessage(MetaMsg)

NewCollationNotifier = _reflection.GeneratedProtocolMessageType('NewCollationNotifier', (_message.Message,), dict(
  DESCRIPTOR = _NEWCOLLATIONNOTIFIER,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.NewCollationNotifier)
  ))
_sym_db.RegisterMessage(NewCollationNotifier)

NewCollationResponse = _reflection.GeneratedProtocolMessageType('NewCollationResponse', (_message.Message,), dict(
  DESCRIPTOR = _NEWCOLLATIONRESPONSE,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.NewCollationResponse)
  ))
_sym_db.RegisterMessage(NewCollationResponse)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'github.com.ethresearch.sharding_p2p_poc.pb.event.event_pb2'
  # @@protoc_insertion_point(class_scope:proto.event.Response)
  ))
_sym_db.RegisterMessage(Response)



_EVENT = _descriptor.ServiceDescriptor(
  name='Event',
  full_name='proto.event.Event',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=438,
  serialized_end=533,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewCollation',
    full_name='proto.event.Event.NewCollation',
    index=0,
    containing_service=None,
    input_type=_NEWCOLLATIONNOTIFIER,
    output_type=_NEWCOLLATIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENT)

DESCRIPTOR.services_by_name['Event'] = _EVENT

# @@protoc_insertion_point(module_scope)
